language: minimal
deploy:
  provider: s3
  access_key_id:
    secure: f/M7CXfG2K9GxUU5sKjRrBwujGicITzw/Gu4pG1qipK6c3ng8wa6HY7SkjdAGpUb8jRK5VHITlB3ZFS0jRI5BQV8VpHuDM6EMYYFGWmuriLbvymm74OhqxDXkfRhh2JQjEwxxBOh80/t9nAcrbb2t3NxQx4/dkHINh0cq25zoPb9HNzciSgFCMCoZWgbBjxYnYhq6vEr8guif0HeW9OGDD5Rj7LJ//SDlJejVViz9fc7oWZbB831a/zgXi/7CowmplwH3qsMK8li10N9oiJexbNV6rvpXdUMtjULNsOMdUGhzRB6fpJP03KQ3IGbBDn5HeOOiQk3QDrXtEHPahkKCtypp8TrHbcBkEKNiXtG2bEgXryb4uJoDBV3BArakkzKjh3RZ9Hl9reeLd/SjBx/uiST0SNghSzvIe/9hCyrneZw5t2ZmEIy9MDVo+ujBwbvBdH79twg015KftQfEax0KOojq0YlsZzSC+FXh7arFyXgvD3aGumgpxBddPlvMtJvUmWIygljRQQk4wUQSN6mViSZ7jq/4KAMxZFgV/1T4O+CYqE4NrBZQVzsfzhrPFyqL7c2S5zTxMeK2dcjT8hROPr94SM/bKnQPNqpM7xsuQWKwFAIs9Ct90Nom928iAvZq1eC0v/pR4xcB5M1RiSSqxVq3Of596rf4gXpzJSCFq8=
  secret_access_key:
    secure: h/RU1+UszZC5WfBeEjY6tMSN0wnRsvkEic18HbSNQRR4MGzCUg+j7cSSeHE9mU0up1YP5sgiP85kgWvg2+j02AL36qGxj9ofHZ7dtaoqAyu5S94GYuSICHx11vkuOjY9snYvPdF5iOF16FDpocyRpt2R+i8twJ2YCUGhWNi7th5HUPJfPqnAXyg9qZlnSfJUB/I2s9BMzDe0RNr0DUQjs80dAMqmeiLN3NKg0n0/AvmKUxjULnO7IKC5aHwEZol+Yhbbsv18BErB2AoGIj1fxvwQZPv15RfEqnLp3N1Ny7x/GYfZnZCmzdgj3C8drFY1pf2vMscWdrwfDgRX+p+viyWe/aC+XwSUW5nSONeRbAtvPXtlyL9NtmFuPVfQTf8QwlK7v8iqOMYzjIKIs0hql21ybPU/ByagxxPOqKYRdm5EpWgFt/aQb7lAq6HAKcwiRVzzVhaW3sNXrUik+tpKRjRItbMeJ0+OJ/4sZo94rvRLqgUhlZvojmRn+F/XN//SZkQZFwznR70E7WEBAVi7smCJtk3EIbyXDpXOoCPSEXsumyNlpy9wKxkHZFUdohMGM5au6FtutkPAL8SVPvILmeKVKczlBff4aj+CXY3ABaTpYWV7Zslt1djV6E2jscnd/K0QXMObHUb+vERZNnmVW2bbLT4u9sZmYd88JbDWsqM=
  bucket: iiif-viewers
  acl: public_read
  on:
    repo: UCLALibrary/iiif-sandbox-simple
branches:
  only:
  - master

