language: minimal
deploy:
  provider: s3
  access_key_id: AKIAINH3LRCOYGNVRWWQ
  secret_access_key:
    secure: 0VjxaZeYvIq3Mug1FYxMp9uM7xlId3QqqzFSFGrdAaX+UkXLGTT44QvmyzA41aXg240AY6oxQ0EaI0nBegZfpyBUHMZSANAy6erWXvedj5Zh+XfnUJOtxwKzRoNRjCA8TJQFRyg7jlyTVz71w/6eSKRuT5mmpwrvZa96PW6OEUwE+tiByrMoxpTh22Q0VYB5Tjxv0JFr0ZooKKOCfrsNZOHnxGHYBnNFaWRxWf2hfqhD9iYDW4td0Tl72M6bsWIOiU+Sbjyq4ApES6Dm4OSGwmiyfbj0/MQk+yfNNkfGb3kUJL9NLIkAoZrWXaLeLYOg1evIN0vg92pYcq/h5VK2lUJLah8i1eifA9jSPCcGvUfYkuFwm5J7GkRLi9hpF1/8PR/eBhsJiIaMQd3z3Y9nSscbwOToPBhPiz4pRVwZ9mthFEDne6+kEOyJq+sz6c4yUMmMAkpyeH0SEgYeHhXpz0DHgr7tzoyHnGOuBr8qLJeXGJa+0oxGWBVHFaA+Z/0yW06IDRtV8fTOBq2qjo90La/e8LKRfGzmiAQghx3FCzLL7AVDjghXxMrO2yQqfgIPEzbrT3n1uc+A2Wq9a1tgDx23/XusKC62LBjm3mdHN+gFprkRLyYxdhlPulAi4d9qmtAB6MbjhjrFR17GQFQSSKGQ720M/NvwPFn16KwEG6M=
  bucket: iiif-viewers
  acl: public_read
  skip_cleanup: true
  on:
    repo: UCLALibrary/iiif-sandbox-simple
branches:
  only:
  - master
