language: minimal
deploy:
  provider: s3
  access_key_id:
    secure: snPsEMdYMhjfjf1vVOGEn1xWkDYGhEX0l5le7/kV7TP7j6veW6snZtS0JBr46RbIsDsXafgw/ENfl9MEUWYfdebQ89eMdqcGTgiwXbmPiErdjXDq1MiAxr5rqIAfPIqRAqbrrwhESr8JTRl6XY15FfJL/FxGX0DgGLFQCLlAGx+owNsUFoLmGWp8qUi5Zo4Lnv9dXK9ii7WS6S8300PVfOmsZGDPgKAM8v6bPIBFgnN4hVfuETXvAfKctgQ+aE6p3aT2ZRxeA++sUlpsIRBIUTxnRMoAW/m1cgkxc4jgeaXT+PzdTZuJRUQWuA/ShTuWdEs/8Pib9MAlkDPoJCa+Oim7qmTaYv+ZjQbQOg0u8sSIBosAaEw6Bc0g7DuvlHAj/EAgfBgNkO3tATA9ruSbDAnivcBJavet3uSsLtVlcox7sdS7b3uzZzEhQufLweLjUNWt1V5UXqXN/2FZDOC6uz1jKzDqrCLcF86AyzpT+ofs3T0Y5SFjeGV638vitfU/9KskXo6x+FsG83ew4/mfXO0Z78A6Aua9FhP1VAuxqlBioisN/5CENX6Djan3m3mAqwZPrxkftWrO1qVsUost8iWOr3DKDfElqsAGnYxlNPg4q/seWiUX/WOZTgcqy8GPPvPnk7O6DY467YbjgRVHassYllpVMdC1AELlsiPS9LY=
  secret_access_key:
    secure: DllEtZADyew/dCscUZkAR9qatsWFA+CarKzbJTgd01f1M//1HGK0hO7rfLucRQW9kNBGbS5d5fpcV74MsK9WBW293dVUX5TGK5ETecidxMC7+skYVr8AKojhW4i2JF425/s21f8YXHeC1bs1VtKB1YPACwSl+KzNnXl5OamjhW4g8J+o8mCUiD/X/tI3+6An99nOt6/CNg2tzTEHkPtn/OkVEbAHr8Hpe0ZVh6GnjufLILadbv6eZzIqYmc9ubYTAvHURfAONfb7GFpA7fKJxrqTkob2iq0bLFhodIO0xv2EV1HDAXgya2s/Whc/ea1uDyG+AAMD3beQuP061n8mQY0aCipKiVr6HCyD06rF1zrQMtalqN82uQDvCQhUm/YluvA3t2RvHA4uIlViX2DAKMuBB3wJvzHX9hcOLtPrG+H0z7uHYly7hJQAmRj1YB/Wx7X7echqaB6dwOXINfI3cbb7ayMesPtBWCi8aCaMKZTGZLF6TobW5AE9JpHlDQ7K7fKvysE+JU5kQc1TwPgPxztymbtBJeyusHvOQxN6uqGVs2FbatUWqOeLCbJDBE/Olg64mU8qzcttmI1cMZTRLBaloeM0eVBYV5dxBUBfMv8r0W+xz5bs3ZBPXs61IVhv05pyg7x+AUdlMqp8vELAzkxUJ4wmqGdW4NH+WW350UM=
  bucket: iiif-viewers
  skip_cleanup: true
  region: us-west-2
branches:
  only:
  - master
