language: minimal
deploy:
  provider: s3
  access_key_id: AKIAINH3LRCOYGNVRWWQ
  secret_access_key:
    secure: QZEzw5ay5aBi6PuqerQRlXU16pefahzVdfYVxsM5mKvbLSe/p4gATQMkDEinVhnxQYnK9z50Iuo5BKllcfcZ3asFyfjBJkzURRq/LBsoANXcYH/O9RHZnLqbL0TIn6Yal7wJxPrk1vg+I70pZ267xhjCmeZvEGH3F6NPBjNDeah3FjPMqVkDxDySTNAF22e3ZrvPHPUDnDbdI/gbAzbo/h6ZMxVMReC8295pPckOmFM+Tod3nzW2K0e8u1fcgApnFchP5q0pS/3O1oR1Yr8he7i/397B3bZCaG/nDlw2/aDCz3xcFN7cCbzbJXSrnkWLjUViknGWbIqeGB6SUxLySJNmAxdlrIorOViOspqlJ/rlInxh7XQMXvF3NJuZx4UtPfIkDHwD+mWIRkzcEYgnwK7Bqn4WtLBHqtPjtRcUu3BXI9Eve/gQCGqcCqVn1Hp38Bumo6Onh/TpN6Kre+nHyO8C0IoHLsJ/ZvY1zigmfIrmIwT6XDvFmNMzCLMgFOAcHnC+/gf5ZZtr3jBh3q5E0uWS0f2PI1i4BCFNqHvTDnkQPne3uaH6zKxPeiJzDG4yOwnLg4HO4WrhAKZFZ3oRgHtP0PTrmU4ewZNqoUOdfJgN94J/p6rgTvE+g4DrsvLuVT1gwv8WfF+F1FIHehTxXWuLzW9JcICZMF11jeHMydM=
  bucket: iiif-viewers
  acl: private
  on:
    repo: UCLALibrary/iiif-sandbox-simple